# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: current-user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='current-user.proto',
  package='current_user',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12\x63urrent-user.proto\x12\x0c\x63urrent_user\"O\n\rSignUpRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04salt\x18\x04 \x01(\t\"!\n\rSignInRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"*\n\x0eGetSaltRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"G\n\x15UpdatePasswordRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x14\n\x0cnew_password\x18\x03 \x01(\t\"\x15\n\x05Reply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x9e\x02\n\x12\x43urrentUserService\x12<\n\x06SignUp\x12\x1b.current_user.SignUpRequest\x1a\x13.current_user.Reply\"\x00\x12<\n\x06SignIn\x12\x1b.current_user.SignInRequest\x1a\x13.current_user.Reply\"\x00\x12>\n\x07GetSalt\x12\x1c.current_user.GetSaltRequest\x1a\x13.current_user.Reply\"\x00\x12L\n\x0eUpdatePassword\x12#.current_user.UpdatePasswordRequest\x1a\x13.current_user.Reply\"\x00\x62\x06proto3'
)




_SIGNUPREQUEST = _descriptor.Descriptor(
  name='SignUpRequest',
  full_name='current_user.SignUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='current_user.SignUpRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='current_user.SignUpRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='current_user.SignUpRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salt', full_name='current_user.SignUpRequest.salt', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=115,
)


_SIGNINREQUEST = _descriptor.Descriptor(
  name='SignInRequest',
  full_name='current_user.SignInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='current_user.SignInRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=150,
)


_GETSALTREQUEST = _descriptor.Descriptor(
  name='GetSaltRequest',
  full_name='current_user.GetSaltRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='current_user.GetSaltRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='current_user.GetSaltRequest.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=194,
)


_UPDATEPASSWORDREQUEST = _descriptor.Descriptor(
  name='UpdatePasswordRequest',
  full_name='current_user.UpdatePasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='current_user.UpdatePasswordRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='current_user.UpdatePasswordRequest.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_password', full_name='current_user.UpdatePasswordRequest.new_password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=267,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='current_user.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='current_user.Reply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=290,
)

DESCRIPTOR.message_types_by_name['SignUpRequest'] = _SIGNUPREQUEST
DESCRIPTOR.message_types_by_name['SignInRequest'] = _SIGNINREQUEST
DESCRIPTOR.message_types_by_name['GetSaltRequest'] = _GETSALTREQUEST
DESCRIPTOR.message_types_by_name['UpdatePasswordRequest'] = _UPDATEPASSWORDREQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPREQUEST,
  '__module__' : 'current_user_pb2'
  # @@protoc_insertion_point(class_scope:current_user.SignUpRequest)
  })
_sym_db.RegisterMessage(SignUpRequest)

SignInRequest = _reflection.GeneratedProtocolMessageType('SignInRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINREQUEST,
  '__module__' : 'current_user_pb2'
  # @@protoc_insertion_point(class_scope:current_user.SignInRequest)
  })
_sym_db.RegisterMessage(SignInRequest)

GetSaltRequest = _reflection.GeneratedProtocolMessageType('GetSaltRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSALTREQUEST,
  '__module__' : 'current_user_pb2'
  # @@protoc_insertion_point(class_scope:current_user.GetSaltRequest)
  })
_sym_db.RegisterMessage(GetSaltRequest)

UpdatePasswordRequest = _reflection.GeneratedProtocolMessageType('UpdatePasswordRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPASSWORDREQUEST,
  '__module__' : 'current_user_pb2'
  # @@protoc_insertion_point(class_scope:current_user.UpdatePasswordRequest)
  })
_sym_db.RegisterMessage(UpdatePasswordRequest)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'current_user_pb2'
  # @@protoc_insertion_point(class_scope:current_user.Reply)
  })
_sym_db.RegisterMessage(Reply)



_CURRENTUSERSERVICE = _descriptor.ServiceDescriptor(
  name='CurrentUserService',
  full_name='current_user.CurrentUserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=293,
  serialized_end=579,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignUp',
    full_name='current_user.CurrentUserService.SignUp',
    index=0,
    containing_service=None,
    input_type=_SIGNUPREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SignIn',
    full_name='current_user.CurrentUserService.SignIn',
    index=1,
    containing_service=None,
    input_type=_SIGNINREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSalt',
    full_name='current_user.CurrentUserService.GetSalt',
    index=2,
    containing_service=None,
    input_type=_GETSALTREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdatePassword',
    full_name='current_user.CurrentUserService.UpdatePassword',
    index=3,
    containing_service=None,
    input_type=_UPDATEPASSWORDREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENTUSERSERVICE)

DESCRIPTOR.services_by_name['CurrentUserService'] = _CURRENTUSERSERVICE

# @@protoc_insertion_point(module_scope)
