# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import setting_pb2 as setting__pb2


class SettingServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/setting.SettingService/List',
                request_serializer=setting__pb2.ListRequest.SerializeToString,
                response_deserializer=setting__pb2.Reply.FromString,
                )
        self.Save = channel.unary_unary(
                '/setting.SettingService/Save',
                request_serializer=setting__pb2.SaveRequest.SerializeToString,
                response_deserializer=setting__pb2.Reply.FromString,
                )
        self.Get = channel.unary_unary(
                '/setting.SettingService/Get',
                request_serializer=setting__pb2.GetRequest.SerializeToString,
                response_deserializer=setting__pb2.Reply.FromString,
                )
        self.Update = channel.unary_unary(
                '/setting.SettingService/Update',
                request_serializer=setting__pb2.UpdateRequest.SerializeToString,
                response_deserializer=setting__pb2.Reply.FromString,
                )
        self.Remove = channel.unary_unary(
                '/setting.SettingService/Remove',
                request_serializer=setting__pb2.RemoveRequest.SerializeToString,
                response_deserializer=setting__pb2.Reply.FromString,
                )


class SettingServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=setting__pb2.ListRequest.FromString,
                    response_serializer=setting__pb2.Reply.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=setting__pb2.SaveRequest.FromString,
                    response_serializer=setting__pb2.Reply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=setting__pb2.GetRequest.FromString,
                    response_serializer=setting__pb2.Reply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=setting__pb2.UpdateRequest.FromString,
                    response_serializer=setting__pb2.Reply.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=setting__pb2.RemoveRequest.FromString,
                    response_serializer=setting__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'setting.SettingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SettingService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/setting.SettingService/List',
            setting__pb2.ListRequest.SerializeToString,
            setting__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/setting.SettingService/Save',
            setting__pb2.SaveRequest.SerializeToString,
            setting__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/setting.SettingService/Get',
            setting__pb2.GetRequest.SerializeToString,
            setting__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/setting.SettingService/Update',
            setting__pb2.UpdateRequest.SerializeToString,
            setting__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/setting.SettingService/Remove',
            setting__pb2.RemoveRequest.SerializeToString,
            setting__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
