# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vault.proto',
  package='vault',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bvault.proto\x12\x05vault\"\x1c\n\x0cVaultRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1a\n\nVaultReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x84\x02\n\x05Vault\x12\x30\n\x04list\x12\x13.vault.VaultRequest\x1a\x11.vault.VaultReply\"\x00\x12\x30\n\x04save\x12\x13.vault.VaultRequest\x1a\x11.vault.VaultReply\"\x00\x12/\n\x03get\x12\x13.vault.VaultRequest\x1a\x11.vault.VaultReply\"\x00\x12\x32\n\x06update\x12\x13.vault.VaultRequest\x1a\x11.vault.VaultReply\"\x00\x12\x32\n\x06remove\x12\x13.vault.VaultRequest\x1a\x11.vault.VaultReply\"\x00\x62\x06proto3'
)




_VAULTREQUEST = _descriptor.Descriptor(
  name='VaultRequest',
  full_name='vault.VaultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='vault.VaultRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)


_VAULTREPLY = _descriptor.Descriptor(
  name='VaultReply',
  full_name='vault.VaultReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='vault.VaultReply.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['VaultRequest'] = _VAULTREQUEST
DESCRIPTOR.message_types_by_name['VaultReply'] = _VAULTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VaultRequest = _reflection.GeneratedProtocolMessageType('VaultRequest', (_message.Message,), {
  'DESCRIPTOR' : _VAULTREQUEST,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:vault.VaultRequest)
  })
_sym_db.RegisterMessage(VaultRequest)

VaultReply = _reflection.GeneratedProtocolMessageType('VaultReply', (_message.Message,), {
  'DESCRIPTOR' : _VAULTREPLY,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:vault.VaultReply)
  })
_sym_db.RegisterMessage(VaultReply)



_VAULT = _descriptor.ServiceDescriptor(
  name='Vault',
  full_name='vault.Vault',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='list',
    full_name='vault.Vault.list',
    index=0,
    containing_service=None,
    input_type=_VAULTREQUEST,
    output_type=_VAULTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='save',
    full_name='vault.Vault.save',
    index=1,
    containing_service=None,
    input_type=_VAULTREQUEST,
    output_type=_VAULTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='vault.Vault.get',
    index=2,
    containing_service=None,
    input_type=_VAULTREQUEST,
    output_type=_VAULTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='update',
    full_name='vault.Vault.update',
    index=3,
    containing_service=None,
    input_type=_VAULTREQUEST,
    output_type=_VAULTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='remove',
    full_name='vault.Vault.remove',
    index=4,
    containing_service=None,
    input_type=_VAULTREQUEST,
    output_type=_VAULTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VAULT)

DESCRIPTOR.services_by_name['Vault'] = _VAULT

# @@protoc_insertion_point(module_scope)
